<? if (count($this->getPages()) > 1): ?>
<div class="wax-paginator-pages">
	<a href="<?=$this->getPageUrl(1)?>" class="wax-repeater-page" data-page="1">«</a>
	<a href="<?=$this->getPrevPageUrl()?>" class="wax-repeater-page" data-page="<?=($this->getPrevPageNumber())?>">&#8249;</a>
	<? foreach ($this->getPages() as $page): ?>
		<? if ($page['current']): ?>
			<a href="<?=$this->getPageUrl($page['page'])?>" class="wax-repeater-page active" data-page="<?=$page['page']?>"><b><?=$page['page']?></b></a>
		<? else: ?>
			<a href="<?=$this->getPageUrl($page['page'])?>" class="wax-repeater-page" data-page="<?=$page['page']?>"><?=$page['page']?></a>
		<? endif; ?>
	<? endforeach; ?>
	<a href="<?=$this->getNextPageUrl()?>" class="wax-repeater-page" data-page="<?=($this->getNextPageNumber())?>">&#8250;</a>
	<a href="<?=$this->getLastPageUrl()?>" class="wax-repeater-page" data-page="<?=($this->getTotalPages())?>">»</a>
	<span class="page-info"><?=$this->getPageInfo()?></span>
</div>
<? endif; ?>