<script>
	$(function(){
		<? if ($this->getPaginator()->getMode() == 'ajax' && $this->getInit()): ?>
			$('#<?=$this->getId()?>').waxrepeater({page:<?=$this->getPage()?>, descriptor:'<?=encode(serialize($this->getDescriptor()))?>'});
		<? endif; ?>

		<? if ($this->getPaginator()->getPaginatorType() == 'more' && $this->getPaginator()->getAutoload()): ?>
			$(document).unbind('scroll').bind('scroll',function(e){
				var repeater = $('#<?=$this->getId()?>'),
					offset = repeater.offset(),
					height = repeater.height(),
					top = offset.top,
					windowHeight = $(window).height(),
					windowTop = $(window).scrollTop();

				if (windowTop + windowHeight >= top + height) {
					repeater.find('.wax-repeater-more').click();
				}
		});
		<? endif; ?>

		<? foreach ($this->getInitScripts() as $one): ?>
			executeFunctionByName('<?=$one['script']?>', window, <?=isset($one['data'])?json_encode($one['data']):'""'?>);
		<? endforeach; ?>
	});
</script>